name: Jency Samuel
author:
  name: Jency Samuel
  email: mail@jencysamuel.com
description: >
  Three-quarter journalist, writer, editor. One-quarter civil engineer.
bio: |
  Hello, world !
  I am a journalist
