name: Jency Samuel
author:
  name: Jency Samuel
  email: mail@jencysamuel.com
description: >
  Three-quarter journalist, writer, editor. One-quarter civil engineer.
bio: |
  Hi there, glad that you stopped by.

  I am a journalist and editor by design and civil engineer by default.

  My articles have appeared in national as well as international publications.
  I edit stories, reports and non-fiction books.

  I write about climate change, alternate energy, rural development,
  biodiversity, sustainability, health, agriculture, etc.
